networks:
  rosnet:
    driver: bridge

services:
  roscore:
    hostname: roscore
    container_name: roscore
    image: rosdemo
    build:
      context: "."
    command: roscore
    networks:
      - rosnet
    tty: true
    stdin_open: true
  test_roscore:
    image: rosdemo
    command: rostopic list
    networks:
      - rosnet
    environment:
      - ROS_MASTER_URI=http://roscore:11311/
    depends_on:
      - roscore
    tty: true
    stdin_open: true
