services:
  foxglove:
    build:
      context: .
      args:
        - SCRIPT_FILE=./foxglove_bridge.sh
    depends_on:
      - roscore
    environment:
      - ROS_MASTER_URI=http://roscore:11311
  rostopic:
    build:
      context: .
      args:
        - SCRIPT_FILE=./rosbag_play.sh
    depends_on:
      - roscore
    environment:
      - ROS_MASTER_URI=http://roscore:11311
  roscore:
    build:
      context: .
      args:
        - SCRIPT_FILE=./roscore.sh
    ports:
      - "11311:11311"
    environment:
      - ROS_MASTER_URI=http://roscore:11311
networks:
  ros_network:
    driver: bridge